# Generated by Django 5.2.8 on 2025-11-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_level",
                    models.CharField(
                        choices=[
                            ("regional", "Regional"),
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        default="regional",
                        max_length=20,
                    ),
                ),
                ("certification_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge",
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        default="white",
                        max_length=20,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight_class", models.CharField(blank=True, max_length=20)),
                ("emergency_contact", models.CharField(max_length=100)),
                ("emergency_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee",
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
