# Generated by Django 5.2.6 on 2025-11-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltRankThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("points_required", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["points_required"],
            },
        ),
        migrations.CreateModel(
            name="BeltRankProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_earned", models.IntegerField()),
                ("promoted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_rank_progress",
                        to="core.trainee",
                    ),
                ),
            ],
            options={
                "ordering": ["-promoted_at"],
            },
        ),
        migrations.CreateModel(
            name="TraineePoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("events_participated", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.trainee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("all_time", "All Time"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                        ],
                        default="all_time",
                        max_length=20,
                    ),
                ),
                (
                    "belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="core.trainee",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("trainee", "timeframe", "year", "month")},
            },
        ),
    ]
