# Generated by Django 4.2.23 on 2025-11-27 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='beltrankprogress',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beltrankprogress',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belt_promotions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beltrankprogress',
            name='promotion_type',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('admin_override', 'Admin Override')], default='automatic', max_length=20),
        ),
    ]
