# Generated by Django 5.2.8 on 2025-11-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_event_archived"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="core_event_archive_d3ec08_idx",
            old_name="core_event_archived_event_date_idx",
        ),
    ]
