# Generated by Django 5.2.6 on 2025-11-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0012_rename_core_event_archived_event_date_idx_core_event_archive_d3ec08_idx",
        ),
        ("core", "0013_match_archived"),
        ("core", "0014_merge_match_archived_branches"),
    ]

    operations = []
