# Generated by Django 5.2.6 on 2025-11-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_merge_20251128_2121"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="match",
            new_name="core_match_archive_63503f_idx",
            old_name="core_match_archived_scheduled_time_idx",
        ),
    ]
