# Generated by Django 5.2.8 on 2025-11-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_trainee_archived"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trainee",
            new_name="core_traine_archive_873752_idx",
            old_name="core_trainee_archived_joined_date_idx",
        ),
    ]
