# Generated by Django 5.2.6 on 2025-11-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_payment_archived"),
        (
            "core",
            "0018_rename_core_trainee_archived_joined_date_idx_core_traine_archive_873752_idx",
        ),
    ]

    operations = []
