# Generated by Django 5.2.8 on 2025-11-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_merge_20251128_2157"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="core_paymen_archive_9421b1_idx",
            old_name="core_payment_archive_payment_date_idx",
        ),
    ]
