# Generated by Django 5.2.8 on 2025-11-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_traineeevaluation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="traineeevaluation",
            new_name="core_traine_trainee_923941_idx",
            old_name="core_trainee_trainee__373947_idx",
        ),
        migrations.RenameIndex(
            model_name="traineeevaluation",
            new_name="core_traine_archive_43d6fb_idx",
            old_name="core_trainee_archive_a84919_idx",
        ),
    ]
