# Generated by Django 5.2.8 on 2026-01-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_core_trainee_trainee__373947_idx_core_traine_trainee_923941_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_archive_63503f_idx',
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['archived', '-created_at'], name='core_match_archive_e7d966_idx'),
        ),
    ]
