# Generated by Django 5.2.8 on 2026-01-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
