# Generated by Django 5.2.8 on 2026-01-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltrankprogress',
            name='new_belt_rank',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beltrankprogress',
            name='old_belt_rank',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beltrankthreshold',
            name='belt_rank',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='belt_rank',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='belt_level',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='belt_rank',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('brown', 'Brown'), ('black', 'Black'), ('master_degree', 'Master Degree')], default='white', max_length=20),
        ),
    ]
