# Generated by Django 5.2.6 on 2026-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_trainee_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeevaluation",
            name="achievement_score",
            field=models.IntegerField(
                default=0, help_text="Score 0-100. Contributes 10% to points."
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="attendance_score",
            field=models.IntegerField(
                default=0, help_text="Score 0-100. Contributes 10% to points."
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="is_points_applied",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="performance_score",
            field=models.IntegerField(
                default=0, help_text="Score 0-100. Contributes 10% to points."
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="sparring_score",
            field=models.IntegerField(
                default=0, help_text="Score 0-100. Contributes 20% to points."
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="total_belt_points",
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text="Calculated points added to trainee total",
            ),
        ),
    ]
