# Generated by Django 5.2.8 on 2026-01-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_traineeevaluation_achievement_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("sparring", "Sparring"),
                    ("penan", "Penan"),
                    ("judo", "Judo"),
                    ("breaking", "Breaking"),
                ],
                default="sparring",
                max_length=20,
            ),
        ),
    ]
