# Generated by Django 4.2.23 on 2026-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_promotion_match',
            field=models.BooleanField(default=False, help_text='If set, judge will score all match types'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c1_breaking_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c1_judo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c1_penan_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c1_sparring_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c2_breaking_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c2_judo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c2_penan_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='c2_sparring_score',
            field=models.IntegerField(default=0),
        ),
    ]
