# Generated by Django 5.2.8 on 2026-01-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the achievement', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the achievement')),
                ('achievement_type', models.CharField(choices=[('competition', 'Competition Win'), ('tournament', 'Tournament Placement'), ('certification', 'Certification Earned'), ('skill', 'Skill Milestone'), ('training', 'Training Achievement'), ('other', 'Other Achievement')], default='other', max_length=20)),
                ('date_earned', models.DateField(help_text='Date the achievement was earned')),
                ('proof_document', models.FileField(blank=True, help_text='Optional proof document or image', null=True, upload_to='achievements/')),
                ('points_awarded', models.IntegerField(default=5, editable=False)),
                ('is_points_applied', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.trainee')),
            ],
            options={
                'ordering': ['-date_earned', '-created_at'],
                'indexes': [models.Index(fields=['trainee', '-date_earned'], name='core_traine_trainee_481c79_idx')],
            },
        ),
    ]
