# Generated by Django 5.2.8 on 2026-01-13 07:02

from django.db import migrations


def fix_belt_thresholds(apps, schema_editor):
    """
    Fix belt rank thresholds to match Trainee.BELT_CHOICES.
    Removes invalid thresholds (yellow, orange, blue) and ensures
    correct thresholds exist for: white, green, brown, black, master_degree
    """
    BeltRankThreshold = apps.get_model("core", "BeltRankThreshold")

    # Delete all existing thresholds
    BeltRankThreshold.objects.all().delete()

    # Create correct thresholds matching Trainee.BELT_CHOICES
    thresholds = [
        ("white", 0, "Starting rank - no points required"),
        ("green", 100, "First promotion - 100 points required"),
        ("brown", 250, "Second promotion - 250 points required"),
        ("black", 500, "Third promotion - 500 points required"),
        ("master_degree", 1000, "Highest rank - 1000 points required"),
    ]

    for belt_rank, points, description in thresholds:
        BeltRankThreshold.objects.create(
            belt_rank=belt_rank, points_required=points, description=description
        )


def reverse_fix_belt_thresholds(apps, schema_editor):
    """Reverse migration - recreate old thresholds."""
    BeltRankThreshold = apps.get_model("core", "BeltRankThreshold")
    BeltRankThreshold.objects.all().delete()

    # Recreate old thresholds (for reverse compatibility)
    old_thresholds = [
        ("white", 0, ""),
        ("yellow", 150, ""),
        ("orange", 350, ""),
        ("green", 600, ""),
        ("blue", 900, ""),
        ("brown", 1300, ""),
        ("black", 1800, ""),
    ]

    for belt_rank, points, description in old_thresholds:
        BeltRankThreshold.objects.create(
            belt_rank=belt_rank, points_required=points, description=description
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_add_trainee_achievement"),
    ]

    operations = [
        migrations.RunPython(fix_belt_thresholds, reverse_fix_belt_thresholds),
    ]
