# Generated by Django 5.2.6 on 2026-01-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_training_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.match",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchresult",
            unique_together={("match", "judge")},
        ),
    ]
